export const quiz = {
    "introduction-to-algebra": [
      {
        subject: 'math',
        type: 'true_or_false',
        question: 'Solving equations involves finding the values of variables that make the equation true.',
        correct: true,
        hint: 'Think about the goal of solving equations.',
        desc: 'yes or no',
      },
      {
        subject: 'math',
        type: 'multiple_choice',
        question: 'What is the solution to the equation 2x + 5 = 15?',
        answers: ['5', '7', '10', '15'],
        correct: 2,
        hint: 'Subtract 5 from both sides and solve for x.',
        desc: 'multiple choice',
      },
      {
        subject: 'math',
        type: 'numeric',
        question: 'Evaluate the expression 3(4x - 2) when x = 5.',
        correct: 54,
        hint: 'Replace x with 5 and simplify.',
        desc: 'analysis',
      },
      {
        subject: 'math',
        type: 'checking',
        question: 'Solve the inequality 2x + 7 > 15, and check if x = 5 is a valid solution.',
        answers: ['-1', '-2', '-3', '2'],
        correct: [true, false, false, true],
        hint: 'Solve the inequality and check the solution.',
        desc: 'guessing',
        status: 'error',
      },
      {
        subject: 'math',
        type: 'true_or_false',
        question: 'Inequalities represent a relationship between two expressions that may not be equal.',
        correct: true,
        hint: 'Consider the nature of inequalities.',
        desc: 'yes or no',
      },
    ],
    "geometry": [
      {
        subject: 'math',
        type: 'true_or_false',
        question: 'The sum of the interior angles of a triangle is always 180 degrees.',
        correct: true,
        hint: 'Think about the properties of triangles.',
        desc: 'yes or no',
      },
      {
        subject: 'math',
        type: 'multiple_choice',
        question: 'What is the area of a rectangle with length 8 units and width 5 units?',
        answers: ['13', '26', '40', '48'],
        correct: 3,
        hint: 'Area = length * width',
        desc: 'multiple choice',
      },
      {
        subject: 'math',
        type: 'numeric',
        question: 'Find the perimeter of a square with side length 12 units.',
        correct: 48,
        hint: 'Perimeter = 4 * side length',
        desc: 'analysis',
      },
      {
        subject: 'math',
        type: 'checking',
        question: 'Determine if a triangle with side lengths 3, 4, and 5 forms a right-angled triangle.',
        answers: ['true', 'false', 'false', 'true'],
        correct: [false, true, true, false],
        hint: 'Use the Pythagorean theorem.',
        desc: 'guessing',
        status: 'error',
      },
      {
        subject: 'math',
        type: 'true_or_false',
        question: 'Similar figures have the same shape but not necessarily the same size.',
        correct: true,
        hint: 'Consider the definition of similar figures.',
        desc: 'yes or no',
      },
    ],
    "trigonometry": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'In a right-angled triangle, the hypotenuse is always opposite the smallest angle.',
          correct: false,
          hint: 'Consider the definition of the hypotenuse.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the value of sin(90 degrees)?',
          answers: ['0', '1', '1/2', '-1'],
          correct: 1,
          hint: 'Recall the values of trigonometric functions.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'If tan(x) = 3/4, what is the value of cos(x)?',
          correct: 4 / 5,
          hint: 'Use the relationship between trigonometric functions.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Solve the equation sin(x) = 1/2, and check if x = 30 degrees is a valid solution.',
          answers: ['true', 'false', 'false', 'true'],
          correct: [false, true, true, false],
          hint: 'Solve the equation and check the solution.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'The Law of Sines is used to find the angles of a triangle when side lengths are known.',
          correct: true,
          hint: 'Consider the applications of the Law of Sines.',
          desc: 'yes or no',
        },
      ],
      "functions-and-graphs": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'A function can have multiple outputs for the same input value.',
          correct: false,
          hint: 'Recall the definition of a function.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'Which of the following graphs represents a quadratic function?',
          answers: ['Line', 'Parabola', 'Exponential curve', 'Hyperbola'],
          correct: 1,
          hint: 'Examine the characteristics of different function graphs.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Find the x-intercept of the function f(x) = 2x - 3.',
          correct: 3 / 2,
          hint: 'Set f(x) to 0 and solve for x.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Determine if the point (4, 7) lies on the graph of the function y = 2x + 1.',
          answers: ['true', 'false', 'false', 'true'],
          correct: [true, false, false, true],
          hint: 'Substitute the coordinates into the function.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'The inverse of a function undoes the effect of the original function.',
          correct: true,
          hint: 'Think about the concept of inverse functions.',
          desc: 'yes or no',
        },
      ],
      "statistics-and-probability": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'In statistics, the median is the middle value of a dataset.',
          correct: true,
          hint: 'Consider the definition of the median.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the probability of rolling a sum of 7 with two six-sided dice?',
          answers: ['1/6', '1/8', '1/12', '1/36'],
          correct: 1/6,
          hint: 'Analyze the possible outcomes of rolling two dice.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Calculate the mean (average) of the following dataset: 4, 7, 9, 12, 15.',
          correct: 9.4,
          hint: 'Add up the values and divide by the number of data points.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'In a deck of cards, what is the probability of drawing a red card and a face card?',
          answers: ['true', 'false', 'false', 'true'],
          correct: [false, true, true, false],
          hint: 'Consider the characteristics of red cards and face cards.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Probability values range from 0 to 100%.',
          correct: false,
          hint: 'Recall the range of probability values.',
          desc: 'yes or no',
        },
      ],
      "pre-calculus": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Exponential functions always have a positive growth rate.',
          correct: true,
          hint: 'Consider the behavior of exponential functions.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'Which of the following sequences is arithmetic?',
          answers: ['2, 4, 8, 16, 32', '3, 6, 9, 12, 15', '1, 3, 9, 27, 81', '5, 10, 20, 40, 80'],
          correct: 3,
          hint: 'Determine the common difference in arithmetic sequences.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Evaluate the limit as x approaches 0 for the function (sin(x))/x.',
          correct: 1,
          hint: 'Apply L Hospitals Rule or use trigonometric limits.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Solve the equation log₂(x) = 3 for x.',
          answers: ['true', 'false', 'false', 'true'],
          correct: [false, true, true, false],
          hint: 'Use properties of logarithmic functions.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Limits can be used to describe the behavior of a function as it approaches a certain point.',
          correct: true,
          hint: 'Consider the definition of limits.',
          desc: 'yes or no',
        },
      ],
      "calculus": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'The derivative of a constant function is always zero.',
          correct: true,
          hint: 'Recall the derivative rules for constant functions.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the derivative of the function f(x) = 3x² + 2x - 1?',
          answers: ['6x + 2', '3x² + 2', '6x - 1', '2x + 2'],
          correct: 0,
          hint: 'Apply the power rule for derivatives.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Find the definite integral of the function f(x) = x² from x = 0 to x = 3.',
          correct: 9,
          hint: 'Apply the fundamental theorem of calculus.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Determine the points of inflection for the function f(x) = x³ - 3x² - 9x.',
          answers: ['true', 'false', 'false', 'true'],
          correct: [false, true, true, false],
          hint: 'Find where the second derivative changes sign.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'The Mean Value Theorem guarantees the existence of a point where the derivative is zero.',
          correct: false,
          hint: 'Consider the conditions of the Mean Value Theorem.',
          desc: 'yes or no',
        },
      ],
      "applied-mathematics": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Financial mathematics involves the application of mathematical methods to financial problems.',
          correct: true,
          hint: 'Consider the scope of financial mathematics.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the present value of $5000 due in 3 years with an annual interest rate of 4%?',
          answers: ['$4512', '$4577', '$4762', '$4852'],
          correct: 0,
          hint: 'Use the present value formula in compound interest.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Solve the exponential growth model A = 2000 * e^(0.05t) for t when A = 3000.',
          correct: 20,
          hint: 'Apply the formula for exponential growth.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Evaluate the expression 2x² - 5x + 3 for x = 2.',
          answers: ['true', 'false', 'false', 'true'],
          correct: [false, true, true, false],
          hint: 'Substitute x = 2 into the expression.',
          desc: 'guessing',
          status: 'error',
        },
        {
            subject: "math",
            type: 'true_or_false',
            question: 'In applied mathematics, modeling involves representing real-world phenomena using mathematical structures.',
            correct: true,
            hint: 'Consider the purpose of mathematical modeling in applied mathematics.',
            desc: 'yes or no',
        },
    ],
    "mathematical-problem-solving": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Mathematical problem-solving always follows a fixed set of steps.',
          correct: false,
          hint: 'Consider the dynamic and creative nature of problem-solving.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the key to successful mathematical problem-solving?',
          answers: ['Memorizing formulas', 'Rote learning', 'Critical thinking and creativity', 'Speed and accuracy'],
          correct: 2,
          hint: 'Reflect on the essential skills for effective problem-solving.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Solve the expression 2x + 3 = 11 for x.',
          correct: 4,
          hint: 'Isolate the variable and solve for its value.',
          desc: 'analysis',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Determine if the solution x = 3 is correct for the equation x^2 - 9 = 0.',
          answers: ['true', 'false'],
          correct: [true, false],
          hint: 'Substitute the solution back into the equation and check.',
          desc: 'guessing',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Problem-solving in mathematics only involves finding numerical solutions.',
          correct: false,
          hint: 'Consider the various aspects and approaches to mathematical problems.',
          desc: 'yes or no',
        },
      ],
      "mathematical-tools": [
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Theorems are mathematical tools used for practical problem-solving.',
          correct: true,
          hint: 'Understand the role of theorems in mathematics.',
          desc: 'yes or no',
        },
        {
          subject: 'math',
          type: 'multiple_choice',
          question: 'What is the purpose of mathematical notation?',
          answers: ['Making equations look complex', 'Facilitating communication and understanding', 'Serving as a form of encryption', 'Avoiding mathematical concepts'],
          correct: 1,
          hint: 'Think about the role of notation in mathematics.',
          desc: 'multiple choice',
        },
        {
          subject: 'math',
          type: 'numeric',
          question: 'Prove that the square root of 2 is irrational.',
          correct: 'The square root of 2 is irrational.',
          hint: 'Use proof techniques to show the irrationality of the square root of 2.',
          desc: 'proof',
        },
        {
          subject: 'math',
          type: 'checking',
          question: 'Check if the statement "All prime numbers are odd" is true.',
          answers: ['true', 'false'],
          correct: [true, false],
          hint: 'Consider examples of prime numbers to check the statement.',
          desc: 'verification',
          status: 'error',
        },
        {
          subject: 'math',
          type: 'true_or_false',
          question: 'Mathematical software and tools are only useful for beginners.',
          correct: false,
          hint: 'Recognize the ongoing significance of mathematical software and tools.',
          desc: 'yes or no',
        },
      ],
  };
  